name: Apply

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "plan"

  apply:
    runs-on: ubuntu-latest
    environment:
      name: apply
    steps:
      - uses: actions/checkout@v4
      - run: echo "apply"
